<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Seed the catalogue carried over from the static site. Re-running updates rows by slug.
     */
    public function run(): void
    {
        foreach ($this->products() as $product) {
            Product::updateOrCreate(['slug' => $product['slug']], $product);
        }
    }

    private function products(): array
    {
        return [
            [
                'slug' => 'spc-natural-oak',
                'name' => 'SPC flooring, natural oak',
                'tag' => 'SPC flooring',
                'category' => 'flooring',
                'price' => 79900,
                'old_price' => 99900,
                'unit' => 'box',
                'image' => 'assets/img7.jpg',
                'description' => 'Rigid stone-polymer core plank with a warm natural oak finish. 100% waterproof, click-lock install, ideal for living rooms, bedrooms and offices.',
                'specs' => ['Coverage' => '2.2 m² per box', 'Thickness' => '5 mm + 1 mm underlay', 'Wear layer' => '0.5 mm', 'Install' => 'Click-lock'],
                'sort_order' => 1,
                'featured_position' => 1,
            ],
            [
                'slug' => 'spc-grey-stone',
                'name' => 'SPC flooring, grey stone',
                'tag' => 'SPC flooring',
                'category' => 'flooring',
                'price' => 84900,
                'old_price' => 104900,
                'unit' => 'box',
                'image' => 'assets/img2.jpg',
                'description' => 'Stone-look SPC tile plank in cool grey. Waterproof and scratch resistant for kitchens and shops.',
                'specs' => ['Coverage' => '2.2 m² per box', 'Thickness' => '5 mm', 'Install' => 'Click-lock'],
                'sort_order' => 2,
                'featured_position' => 5,
            ],
            [
                'slug' => 'porcelain-matt-concrete',
                'name' => 'Porcelain tile, matt concrete',
                'tag' => 'Tiles',
                'category' => 'flooring',
                'price' => 42900,
                'old_price' => 52900,
                'unit' => 'box',
                'image' => 'assets/img12.jpg',
                'description' => '60 x 60 cm matt porcelain tile with a modern concrete look. Hard wearing indoors and out.',
                'specs' => ['Size' => '60 x 60 cm', 'Coverage' => '1.44 m² per box', 'Finish' => 'Matt'],
                'sort_order' => 3,
                'featured_position' => null,
            ],
            [
                'slug' => 'wpc-walnut',
                'name' => 'WPC flooring, walnut',
                'tag' => 'WPC flooring',
                'category' => 'flooring',
                'price' => 89900,
                'old_price' => 119900,
                'unit' => 'box',
                'image' => 'assets/img13.jpg',
                'description' => 'Soft-underfoot wood-polymer plank in rich walnut. Quiet, warm and waterproof.',
                'specs' => ['Coverage' => '2 m² per box', 'Thickness' => '8 mm', 'Install' => 'Click-lock'],
                'sort_order' => 4,
                'featured_position' => 6,
            ],
            [
                'slug' => 'fluted-wpc-oak',
                'name' => 'Fluted WPC wall panel, oak',
                'tag' => 'Wall panels',
                'category' => 'interior',
                'price' => 149900,
                'old_price' => 214000,
                'unit' => 'pack of 10',
                'image' => 'assets/img8.jpg',
                'description' => 'Slatted feature-wall panels in light oak. Fire-rated, waterproof and fixed with clips or adhesive.',
                'specs' => ['Panel size' => '2.9 m x 16 cm', 'Pack covers' => '4.6 m²', 'Fire rating' => 'B1'],
                'sort_order' => 5,
                'featured_position' => 2,
            ],
            [
                'slug' => 'pu-stone-slate',
                'name' => 'PU stone panel, slate',
                'tag' => 'PU stone',
                'category' => 'interior',
                'price' => 119900,
                'old_price' => 169900,
                'unit' => 'carton of 4',
                'image' => 'assets/img14.jpg',
                'description' => 'Lightweight polyurethane panels with a realistic split-slate texture. Easy to cut and glue.',
                'specs' => ['Panel size' => '120 x 60 cm', 'Weight' => '1.5 kg per panel'],
                'sort_order' => 6,
                'featured_position' => 7,
            ],
            [
                'slug' => 'marble-sheet-carrara',
                'name' => 'Marble sheet, Carrara white',
                'tag' => 'Marble sheet',
                'category' => 'interior',
                'price' => 69900,
                'old_price' => 99900,
                'unit' => 'sheet',
                'image' => 'assets/img15.jpg',
                'description' => 'High-gloss UV marble sheet for bathrooms, kitchens and TV walls. The marble look without the weight.',
                'specs' => ['Size' => '2.44 x 1.22 m', 'Thickness' => '3 mm', 'Finish' => 'High gloss UV'],
                'sort_order' => 7,
                'featured_position' => 8,
            ],
            [
                'slug' => 'acoustic-wall-panel',
                'name' => 'Acoustic wall panel, walnut',
                'tag' => 'Wall panels',
                'category' => 'interior',
                'price' => 189900,
                'old_price' => 239900,
                'unit' => 'pack of 4',
                'image' => 'assets/img11.jpg',
                'description' => 'Walnut slats on felt backing that absorb sound. Perfect for offices, studios and home cinemas.',
                'specs' => ['Panel size' => '2.4 m x 60 cm', 'Backing' => '9 mm PET felt'],
                'sort_order' => 8,
                'featured_position' => null,
            ],
            [
                'slug' => 'wpc-ceiling-panel',
                'name' => 'WPC ceiling panel, white',
                'tag' => 'Ceiling',
                'category' => 'interior',
                'price' => 59900,
                'old_price' => null,
                'unit' => 'pack of 10',
                'image' => 'assets/img16.jpg',
                'description' => 'Clean white tongue-and-groove ceiling panels. Moisture proof and termite proof.',
                'specs' => ['Panel size' => '2.9 m x 20 cm', 'Pack covers' => '5.8 m²'],
                'sort_order' => 9,
                'featured_position' => null,
            ],
            [
                'slug' => 'exterior-wpc-teak',
                'name' => 'Exterior WPC panel, teak',
                'tag' => 'Cladding',
                'category' => 'exterior',
                'price' => 129900,
                'old_price' => 159900,
                'unit' => 'pack of 6',
                'image' => 'assets/img9.jpg',
                'description' => 'UV-stable co-extruded cladding for facades and fences. Will not rot, warp or fade in the Tanzanian sun.',
                'specs' => ['Panel size' => '2.9 m x 21.9 cm', 'UV warranty' => '10 years'],
                'sort_order' => 10,
                'featured_position' => 3,
            ],
            [
                'slug' => 'exterior-wpc-charcoal',
                'name' => 'Exterior WPC panel, charcoal',
                'tag' => 'Cladding',
                'category' => 'exterior',
                'price' => 129900,
                'old_price' => null,
                'unit' => 'pack of 6',
                'image' => 'assets/img17.jpg',
                'description' => 'Modern charcoal facade cladding with a brushed wood grain.',
                'specs' => ['Panel size' => '2.9 m x 21.9 cm', 'UV warranty' => '10 years'],
                'sort_order' => 11,
                'featured_position' => null,
            ],
            [
                'slug' => 'wpc-installation-clips',
                'name' => 'WPC installation clips',
                'tag' => 'Fixings',
                'category' => 'accessories',
                'price' => 14900,
                'old_price' => null,
                'unit' => 'bag of 100',
                'image' => 'assets/img18.jpg',
                'description' => 'Stainless clips and screws for hidden-fix wall and cladding panels.',
                'specs' => ['Material' => 'Stainless steel', 'Fits' => 'All REX WPC panels'],
                'sort_order' => 12,
                'featured_position' => null,
            ],
            [
                'slug' => 'construction-adhesive',
                'name' => 'Construction adhesive',
                'tag' => 'Adhesives',
                'category' => 'accessories',
                'price' => 12900,
                'old_price' => null,
                'unit' => 'tube',
                'image' => 'assets/img19.jpg',
                'description' => 'High-grab adhesive for PU stone, marble sheet and panels. Bonds in minutes.',
                'specs' => ['Volume' => '300 ml', 'Coverage' => 'About 2 m²'],
                'sort_order' => 13,
                'featured_position' => null,
            ],
            [
                'slug' => 'skirting-oak',
                'name' => 'Skirting, oak',
                'tag' => 'Trims',
                'category' => 'accessories',
                'price' => 9900,
                'old_price' => null,
                'unit' => '2.4 m length',
                'image' => 'assets/img5.jpg',
                'description' => 'Matching skirting for a clean finish between floor and wall.',
                'specs' => ['Height' => '8 cm', 'Length' => '2.4 m'],
                'sort_order' => 14,
                'featured_position' => null,
            ],
            [
                'slug' => 'marble-joint-profile',
                'name' => 'Marble sheet joint profile',
                'tag' => 'Trims',
                'category' => 'accessories',
                'price' => 7900,
                'old_price' => null,
                'unit' => '2.9 m length',
                'image' => 'assets/img20.jpg',
                'description' => 'Aluminium H-profile for neat joins between marble sheets.',
                'specs' => ['Material' => 'Aluminium', 'Length' => '2.9 m'],
                'sort_order' => 15,
                'featured_position' => null,
            ],
            [
                'slug' => 'melamine-walnut',
                'name' => 'Melamine board, walnut',
                'tag' => 'Melamine',
                'category' => 'boards',
                'price' => 89900,
                'old_price' => 109900,
                'unit' => 'sheet',
                'image' => 'assets/img10.jpg',
                'description' => '18 mm melamine-faced chipboard for wardrobes, kitchens and office furniture.',
                'specs' => ['Size' => '2.44 x 1.22 m', 'Thickness' => '18 mm'],
                'sort_order' => 16,
                'featured_position' => 4,
            ],
            [
                'slug' => 'mdf-white-gloss',
                'name' => 'MDF board, white gloss',
                'tag' => 'MDF',
                'category' => 'boards',
                'price' => 99900,
                'old_price' => null,
                'unit' => 'sheet',
                'image' => 'assets/img6.jpg',
                'description' => 'High-gloss white MDF for modern kitchen doors and cabinetry.',
                'specs' => ['Size' => '2.44 x 1.22 m', 'Thickness' => '18 mm'],
                'sort_order' => 17,
                'featured_position' => null,
            ],
        ];
    }
}
