@extends('layouts.app')

@section('content')
<section class="relative overflow-hidden bg-[oklch(0.2_0.05_255)] text-white"><div class="relative mx-auto max-w-7xl px-4 py-16 md:py-20"><p class="font-mono text-xs uppercase tracking-[0.3em] text-accent">Shop</p><h1 class="mt-2 text-6xl font-black md:text-8xl" data-shop-title="">All materials</h1><p class="mt-3 max-w-lg text-white/75" data-shop-sub="">Floors, walls, cladding, accessories and boards. Free delivery across Tanzania.</p></div></section><div class="sticky top-[105px] z-30 border-b bg-background/95 backdrop-blur"><div class="mx-auto flex max-w-7xl flex-col gap-3 px-4 py-3 md:flex-row md:items-center md:justify-between"><div class="-mx-4 flex gap-2 overflow-x-auto px-4 md:mx-0 md:px-0"><button class="shrink-0 rounded-sm px-3 py-1.5 text-sm font-semibold transition-colors bg-primary text-primary-foreground" data-cat-chip="all" type="button">All</button><button class="shrink-0 rounded-sm px-3 py-1.5 text-sm font-semibold transition-colors bg-muted hover:bg-secondary" data-cat-chip="flooring" type="button">Flooring</button><button class="shrink-0 rounded-sm px-3 py-1.5 text-sm font-semibold transition-colors bg-muted hover:bg-secondary" data-cat-chip="interior" type="button">Interior walls</button><button class="shrink-0 rounded-sm px-3 py-1.5 text-sm font-semibold transition-colors bg-muted hover:bg-secondary" data-cat-chip="exterior" type="button">Exterior cladding</button><button class="shrink-0 rounded-sm px-3 py-1.5 text-sm font-semibold transition-colors bg-muted hover:bg-secondary" data-cat-chip="accessories" type="button">Accessories</button><button class="shrink-0 rounded-sm px-3 py-1.5 text-sm font-semibold transition-colors bg-muted hover:bg-secondary" data-cat-chip="boards" type="button">Furniture boards</button></div><input class="h-9 w-full min-w-0 rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none selection:bg-primary selection:text-primary-foreground file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-muted-foreground disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm dark:bg-input/30 focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 md:w-72" data-slot="input" id="shop-search" placeholder="Search e.g. oak, marble, clips" type="search"/></div></div><main class="mx-auto max-w-7xl px-4 py-12"><p class="mb-6 text-sm text-muted-foreground" data-shop-count="">{{ $products->count() }} {{ Str::plural('product', $products->count()) }}</p><div class="grid gap-x-6 gap-y-12 sm:grid-cols-2 lg:grid-cols-4" id="shop-grid">
@foreach ($products as $product)
@include('partials.product-card')
@endforeach
</div><p class="py-16 text-center text-muted-foreground" hidden id="shop-empty">No products match your search.</p></main>
@endsection
